#!/usr/bin/env pwsh
# =============================================================================
# figma-check-orphans.ps1 — find features whose design context silently died
# =============================================================================
# PowerShell 7+ port of scripts/bash/figma-check-orphans.sh (same contract).
#
# 2.0.0 made a Figma link the sole trigger for design context. Before it, a
# mapped pageToPackageMapping was enough, so a spec generated by 1.6.x can carry
# a full design section that records NO url — it reads "None — context derived
# from page mapping."
#
# Under 2.0.0 such a feature is silently dead: the link recovery in
# figma-ensure-context parses urls out of the committed spec.md, and with none to
# find it falls through to `no-figma-link`, under which the agent says nothing
# about Figma at all. plan.md and tasks.md quietly lose the design context
# spec.md still displays, and nothing reports it.
#
# Usage: figma-check-orphans.ps1 [--specs-dir <path>] [--strict]
# =============================================================================
$ErrorActionPreference = 'Stop'
. "$PSScriptRoot/figma-common.ps1"

$specsDir = ''
$strict = $false
$i = 0
while ($i -lt $args.Count) {
    switch -Regex ($args[$i]) {
        '^--specs-dir$' { $specsDir = [string]$args[$i + 1]; $i += 2; continue }
        '^--config$'    { $env:FIGMA_CONFIG = [string]$args[$i + 1]; $i += 2; continue }
        '^--strict$'    { $strict = $true; $i += 1; continue }
        default         { Write-FigmaStderr "ERROR: unknown arg '$($args[$i])'"; exit 1 }
    }
}

$root = Get-FigmaRepoRoot
if (-not $specsDir) { $specsDir = Join-Path $root 'specs' }

$scanned = 0
$healthy = 0
$orphans = @()

if (Test-Path -LiteralPath $specsDir -PathType Container) {
    $docs = Get-ChildItem -LiteralPath $specsDir -Directory -ErrorAction SilentlyContinue |
        ForEach-Object { Join-Path $_.FullName 'spec.md' } |
        Where-Object { Test-Path -LiteralPath $_ -PathType Leaf } |
        Sort-Object
    foreach ($doc in $docs) {
        # Only documents the extension actually produced: a figma.com url
        # mentioned in prose is not a design section.
        if (-not (Select-String -LiteralPath $doc -SimpleMatch -Pattern 'speckit-figma:section phase=spec' -Quiet)) {
            continue
        }
        $scanned++
        $feature = Split-Path -Leaf (Split-Path -Parent $doc)
        $parsed = @(& "$PSScriptRoot/figma-parse-links.ps1" (Get-Content -LiteralPath $doc -Raw))
        if (($parsed | Where-Object { $_ -match '"fileId"' }).Count -gt 0) {
            $healthy++
        } else {
            $rel = $doc.Replace("$root/", '').Replace("$root\", '')
            $orphans += [ordered]@{ feature = $feature; doc = $rel; reason = 'no-link-recorded' }
        }
    }
}

if ($orphans.Count -gt 0) {
    Write-FigmaStderr "WARN: $($orphans.Count) feature(s) carry a Figma design section but no Figma link."
    Write-FigmaStderr '      They were generated before 2.0.0, when the page mapping was enough to trigger design context.'
    Write-FigmaStderr '      Under 2.0.0 the link is the trigger, so /speckit.plan and /speckit.tasks now add NOTHING about Figma to those features — silently.'
    Write-FigmaStderr '      Fix: paste the Figma link of the frame each one targets into its spec.md (inside the design section), or set autoIntrospect on the target.'
    foreach ($o in $orphans) { Write-FigmaStderr "      - $($o.feature) ($($o.doc))" }
}

ConvertTo-FigmaJson ([ordered]@{
    scanned = $scanned
    healthy = $healthy
    orphans = @($orphans)
})

if ($strict -and $orphans.Count -gt 0) { exit 1 }
