#!/usr/bin/env bash
# =============================================================================
# figma-check-orphans.sh — find features whose design context silently died
# =============================================================================
# 2.0.0 made a Figma link the sole trigger for design context. Before it, a
# mapped `pageToPackageMapping` was enough, so a spec generated by 1.6.x can
# carry a full design section that records NO url — it reads "None — context
# derived from page mapping."
#
# Under 2.0.0 such a feature is silently dead. The link recovery in
# figma-ensure-context parses urls out of the committed spec.md; with none to
# find it falls through to `no-figma-link`, under which the agent is instructed
# to say nothing about Figma at all. So `plan.md` and `tasks.md` quietly lose the
# design context `spec.md` still displays — and nothing anywhere reports it. That
# is the one failure mode this extension has that produces no signal.
#
# This check reports those features. It never edits a document: pasting the right
# link back is a human decision (which frame the feature targeted is exactly what
# the old spec failed to record).
#
# Usage:
#   figma-check-orphans.sh [--specs-dir <path>] [--strict]
# Prints a JSON report on stdout:
#   { "scanned": N, "orphans": [ {feature, doc, reason} ], "healthy": N }
# reason is "no-link-recorded" (an era-1.6.0 mapping-derived section).
# Exit 0 always, unless --strict and at least one orphan was found.
# =============================================================================
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=./figma-common.sh
source "${SCRIPT_DIR}/figma-common.sh"
figma_require jq

SPECS_DIR=""
STRICT="false"
while [[ $# -gt 0 ]]; do
  case "$1" in
    --specs-dir) SPECS_DIR="$2"; shift 2 ;;
    --config) FIGMA_CONFIG="$2"; export FIGMA_CONFIG; shift 2 ;;
    --strict) STRICT="true"; shift ;;
    *) echo "ERROR: unknown arg '$1'" >&2; exit 1 ;;
  esac
done

ROOT="$(figma_repo_root)"
[[ -n "$SPECS_DIR" ]] || SPECS_DIR="${ROOT}/specs"

SCANNED=0
HEALTHY=0
ORPHANS="[]"

if [[ -d "$SPECS_DIR" ]]; then
  while IFS= read -r doc; do
    [[ -n "$doc" ]] || continue
    # Only documents the extension actually produced: a figma.com url mentioned
    # in prose is not a design section, and neither is a spec that never had one.
    grep -qF 'speckit-figma:section phase=spec' "$doc" || continue
    SCANNED=$(( SCANNED + 1 ))
    FEATURE="$(basename "$(dirname "$doc")")"
    if "${SCRIPT_DIR}/figma-parse-links.sh" < "$doc" | grep -q '"fileId"'; then
      HEALTHY=$(( HEALTHY + 1 ))
    else
      ORPHANS="$(jq -c --arg f "$FEATURE" --arg d "${doc#"$ROOT"/}" \
        '. + [{feature:$f, doc:$d, reason:"no-link-recorded"}]' <<< "$ORPHANS")"
    fi
  done < <(find "$SPECS_DIR" -mindepth 2 -maxdepth 2 -name 'spec.md' 2>/dev/null | sort)
fi

COUNT="$(jq -r 'length' <<< "$ORPHANS")"
if [[ "$COUNT" -gt 0 ]]; then
  echo "WARN: ${COUNT} feature(s) carry a Figma design section but no Figma link." >&2
  echo "      They were generated before 2.0.0, when the page mapping was enough to trigger design context." >&2
  echo "      Under 2.0.0 the link is the trigger, so /speckit.plan and /speckit.tasks now add NOTHING about Figma to those features — silently." >&2
  echo "      Fix: paste the Figma link of the frame each one targets into its spec.md (inside the design section), or set autoIntrospect on the target." >&2
  jq -r '.[] | "      - \(.feature) (\(.doc))"' <<< "$ORPHANS" >&2
fi

jq -n --argjson scanned "$SCANNED" --argjson healthy "$HEALTHY" --argjson orphans "$ORPHANS" \
  '{scanned:$scanned, healthy:$healthy, orphans:$orphans}'

if [[ "$STRICT" == "true" && "$COUNT" -gt 0 ]]; then
  exit 1
fi
